version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sample_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  test:
    build: .
    command: python manage.py test
    volumes:
      - .:/app
    depends_on:
      - db

  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"

volumes:
  postgres_data:
