# Generated by Django 3.0.1 on 2023-06-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
