# Generated by Django 3.0.1 on 2023-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_apartment_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
