# Generated by Django 3.0.1 on 2023-07-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20230711_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='region_id',
        ),
    ]
